version: '3.1'

services:
  mongodb:
    image: quay.io/debezium/example-mongodb:2.1
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=debezium
      - MONGODB_PASSWORD=dbz
  debezium:
    image: debezium/server
    environment:
      - debezium_source_mongodb_connection_string=$DEBEZIUM_MONGO
    volumes:
      - ./debezium:/debezium/conf
    depends_on:
      - mongodb