version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./scripts/init.sh:/usr/local/bin/init.sh
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=debezium
      - MONGODB_PASSWORD=dbz
    command: ["--replSet", "rs0", "--dbpath", "/data/db", "--bind_ip_all"]
  debezium:
    image: debezium/server
    environment:
      - debezium_source_mongodb_connection_string=$DEBEZIUM_MONGO
    volumes:
      - ./debezium:/debezium/conf
    depends_on:
      - mongodb